#!/bin/sh
[[ "$(cat /sys/class/net/wlp0s20u3/operstate)" = 'down' ]] && exit

QUALITY=$(grep wlp0s20u3 /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

echo $QUALITY% # full text
echo $QUALITY% # short text
if [[ $QUALITY -ge 80 ]]; then
echo "#00FF00"
elif [[ $QUALITY -lt 80 ]]; then
echo "#FFF600"
elif [[ $QUALITY -lt 60 ]]; then
echo "#FFAE00"
elif [[ $QUALITY -lt 40 ]]; then
echo "#FF0000"
fi